### ISSUE TITLE
"private.key" file in wrong folder

### ISSUE THREAD

**Issue by Rafalkufel** [docusign/code-examples-python#21]
When I try to run first example (`Use embedded signing`), on route `/ds/must_authenticate`, when I choose option `JSON Web Token` from the list "Please choose OAuth2.0 grant type",  I get error: `ValueError: Could not deserialize key data.`

In my opinion this error stem from wrong location of "private.key" file. Originally file is located in `./app/private.key`. After I moved it to `./private.key` that error doesn't appeare anymore.

ubuntu 20.04

python 3.8.5
flask 1.1.1
docusign-esign 3.6.0

**Comment by ivdinkovds** [comment]
I am sorry you are having this issue. Thank you for notifying us. It looks like a bug during Quickstart example creation

**Comment by InbarGazit** [comment]
This issue has been resolved.
