### ISSUE TITLE
How to assign SignHere Tabs in Bulk Send Envelope

### ISSUE THREAD

**Issue by maaqib121** [docusign/code-examples-python#25]
I have set up every other thing for bulk send and it's working pretty nicely. Following is the placeholder snippet which is being replaced by the original recipients in the bulk list:

```
        signer = Signer(name='Multi Bulk Recipient::signer', email='multiBulkRecipients-signer@docusign.com',
                        role_name='signer', note='', routing_order='1', status='created', delivery_method='email',
                        recipient_id='13', recipient_type='signer')
        sign_here = SignHere(anchor_string='**Employee Signature**', anchor_units='pixels',
                             anchor_y_offset='10', anchor_x_offset='20')
        signer.tabs = Tabs(sign_here_tabs=[sign_here])

       envelope_api.create_recipient(ACCOUNT_ID, envelope_id, recipients=Recipients(signers=[signer]))
```

But it is not creating the SignHere tab in the document. This same code was working in case of single envelope but that's not the case here. Can anyone help?

**Comment by bendowlingtech** [comment]
Hi maaqib121, 

Have you had a look at our documentation here: https://developers.docusign.com/docs/esign-rest-api/how-to/bulk-send-envelopes/

**Comment by maaqib121** [comment]
I have looked upon and followed each and every step of it as well.

**Comment by InbarGazit** [comment]
Sorry for the delay @maaqib121 can you please let us know if you still need help on this issue?
