### ISSUE TITLE
Trying to run the code

### ISSUE THREAD

**Issue by davehodg** [docusign/code-examples-python#29]
Clean checkout. I believe I've got the credentials correct. Click on "Use embedded signing" and it sends me to DocuSign login, this then tells me "There are no redirect URIs registered with DocuSign":

![image](https://user-images.githubusercontent.com/922517/132706076-d1f8ecd7-1470-428b-b3d9-cd2dc770a590.png)

**Comment by InbarGazit** [comment]
You need to go the [Apps and Keys ](https://admindemo.docusign.com/authenticate?goTo=appsAndKeys)page and find the IK and add the URI to the list. 
Alternatively, you can use [QuicksStart](https://developers.docusign.com/docs/esign-rest-api/quickstart/) and it will set the IK for you just the way it's needed to run.
