### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by neoluu** [docusign/code-examples-python#32]
Hi,

Trying to test bulk user export script, but get following error trying to import. Can you advise what module is required?

ModuleNotFoundError: No module named 'app'

Thx

**Comment by EdwinMoralesDS** [comment]
Hello @neoluu , I'm unable to recreate your error  when I run "python run.py" and browse to the "Bulk export user data" option in the website from the sample app. Are you trying to access this the same way or are you running the script differently?

The module app should refer to the app folder that is included when you download the complete project so yo shouldn't have to install anything else for this module. Have you renamed any of the folders?

**Comment by InbarGazit** [comment]
This was fixed.
