### ISSUE TITLE
Run example "eg008_create_template.py"

### ISSUE THREAD

**Issue by TTlous** [docusign/code-examples-python#33]

**Comment by TTlous** [comment]
Hi, 

How can we run example "eg008_create_template.py"

Thanks!

**Comment by LarryKlugerDS** [comment]
Just run the example. It should then create a template in your developer test account on the demo environment.
If it doesn't, ask for help in StackOverflow and include the DocuSignAPI tag.

**Comment by TTlous** [comment]
What do you mean by "developer test account"?
The DocuSign account?

Thanks!

**Comment by InbarGazit** [comment]
This was fixed.
