### ISSUE TITLE
question on app_url

### ISSUE THREAD

**Issue by AdForte** [docusign/code-examples-python#35]
I do not know what to put in the config file ds_config.py for this fields: 

"app_url": "http://localhost:3000",  # The URL of the application. Eg http://localhost:5000
    # NOTE: You must add a Redirect URI of appUrl/ds/callback to your Integration Key.
    #       Example: http://localhost:5000/ds/callback

Where to find the application url? And why and how to add ds/callback to integration Key?
Thank you for your answers.
regards

**Comment by asingh611** [comment]
Hello, that app_url should be where the application will start running when you run the project (keeping it as the current value would mean that the code examples application should run on your localhost at port 3000)

What the other note refers to is when you application goes through the consent/authentication process (e.g. https://developers.docusign.com/platform/auth/authcode/authcode-get-token/), the application will redirect to the DocuSign login screen and once the user finishes with that, DocuSign needs to know where to redirect back to after granting consent/logging in is completed. The set of URLs that are valid for this redirect for a particular integration are controlled within your DocuSign account under Settings > Apps and Keys and editing the specific integration key (https://developers.docusign.com/platform/configure-app/). There will be a section to specify the valid Redirect URIs for this integration. If you downloaded this project from the Quickstart page (https://developers.docusign.com/docs/esign-rest-api/quickstart/), this may have already been configured for you

Let me know if that helped

**Comment by AdForte** [comment]
Thanks for your help!
