### ISSUE TITLE
Disable redirect after document signing

### ISSUE THREAD

**Issue by Podolyan98** [docusign/code-examples-python#37]
Is it possible to disable the [return_url](https://github.com/docusign/code-examples-python/blob/master/app/eSignature/examples/eg016_set_tab_values.py#L65C14-L65C14) in the [createRecipient](https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/) endpoint? Or maybe there is another way to get the link to the Envelope?

**Comment by mike-mej** [comment]
Hello @Podolyan98 

Thanks for contacting us.

Regarding this, It is not the possibility to disable it.

On how else to get the singing url : 
You can either choose captive/embedded signing and get the URL through that call, or use remote signing and get access to the envelope via email.

Please check the following documentation:
https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/embedding/

I hope the above helps.

**Comment by InbarGazit** [comment]
What do you want the end-user to see after they finish singing?

**Comment by Podolyan98** [comment]
@mike-mej, @InbarGazit  I would like to receive a link just like when sending an Envelope via Email (eg009_use_template.py). First, I receive an email with a link to the document. After signing, I can come back in a few days and see the document

![image](https://github.com/docusign/code-examples-python/assets/68119338/ed635133-bbcc-408e-98c2-6e0401c8b75e)

**Comment by mike-mej** [comment]
@Podolyan98 

According to this you are looking for remote signing,

In that case you will need to remove the ClientUserId when defining the recipient.
To clarify, if you exclude the Client User ID when specifying the recipient, they will receive an email link for signing without the need for a signing session call. In the case where a recipient has a Client User ID, they will be considered a captive recipient and will not receive an email invitation. By removing the Client User ID, the recipient will be treated as a standard Remote recipient and will receive email notifications.

**Comment by InbarGazit** [comment]
"come back in a few days" what does that mean? using the same link? the link may have expired by then, you will need to generate a new one

**Comment by InbarGazit** [comment]
@Podolyan98  can you please explain if you still need help here?

**Comment by Podolyan98** [comment]
@InbarGazit  Looks like I solved the problem by using a fake `recipient_id`:

```
class CreateRecipientView:

    @classmethod
    def worker(cls, args):
        envelope_args = args['envelope_args']
        api_client = create_api_client(base_path=args['base_path'], access_token=args['access_token'])
        envelope_api = EnvelopesApi(api_client)
        recipient_view_request = RecipientViewRequest(
            authentication_method='None',
            return_url=envelope_args['return_url'],
            user_name=envelope_args['signer_name'],
            email=envelope_args['signer_email'],
            recipient_id=uuid.uuid4().int & (1<<24)-1,
        )
        results = envelope_api.create_recipient_view(
            account_id=args['account_id'],
            envelope_id=envelope_args['envelope_id'],
            recipient_view_request=recipient_view_request
        )
        return results
```
